version: "3"
services:
    mysql_container:
        build: ~/Desktop/repo-idp/ProiectIDP/database
        networks: 
            - app
        ports: 
            - "3306:3306"
    worker1:
        build: ~/Desktop/repo-idp/ProiectIDP/worker1
        networks:
            - app
    worker2:
        build: ~/Desktop/repo-idp/ProiectIDP/worker2
        networks:
            - app
networks:
    app:
    
